{{- $existing := (lookup "v1" "Secret" .Values.tenant "openshell-gateway-secrets") -}}
{{- $handshake := (get (default dict $existing.data) "ssh-handshake-secret") | default (randAlphaNum 32 | b64enc) -}}
apiVersion: v1
kind: Secret
metadata:
  name: openshell-credentials-secrets
  namespace: {{ .Values.tenant }}
  labels:
    {{- include "openshell.labels" . | nindent 4 }}
type: Opaque
data:
  placeholder-secret: {{ "changeme" | b64enc | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: openshell-gateway-secrets
  namespace: {{ .Values.tenant }}
  labels:
    {{- include "openshell.labels" . | nindent 4 }}
type: Opaque
data:
  ssh-handshake-secret: {{ $handshake | quote }}
