# Shipwright Build for weather-service agent (OpenShift)
# Uses OpenShift internal registry instead of Kind registry
apiVersion: shipwright.io/v1beta1
kind: Build
metadata:
  name: weather-service
  namespace: team1
  labels:
    app.kubernetes.io/created-by: e2e-test
    app.kubernetes.io/name: weather-service
    kagenti.io/type: agent
    protocol.kagenti.io/a2a: ""
    kagenti.io/framework: LangGraph
  annotations:
    # Store agent configuration for finalization
    kagenti.io/agent-config: |
      {
        "protocol": "a2a",
        "framework": "LangGraph",
        "createHttpRoute": false
      }
spec:
  source:
    type: Git
    git:
      # TODO: Change back to kagenti/agent-examples after PR merged
      # PR: https://github.com/kagenti/agent-examples/pull/XXX
      url: https://github.com/ladas/agent-examples
      revision: genai-autoinstrumentation
    contextDir: a2a/weather_service
  strategy:
    name: buildah
    kind: ClusterBuildStrategy
  paramValues:
    - name: dockerfile
      value: Dockerfile
  output:
    image: image-registry.openshift-image-registry.svc:5000/team1/weather-service:v0.0.1
  timeout: 15m
  retention:
    succeededLimit: 3
    failedLimit: 3
