{{- if .Values.components.mcpGateway.enabled }}
# Gateway resource for mcp-gateway. The mcp-gateway controller (v0.6.0+)
# manages the broker-router deployment and routes automatically via the
# MCPGatewayExtension CR created by the mcp-gateway Helm chart.
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: mcp-gateway
  namespace: "{{ .Values.mcpGateway.namespaces.gatewaySystem }}"
  annotations:
    networking.istio.io/service-type: ClusterIP
  labels:
    gateway.io/name: mcp-gateway
    istio: ingressgateway
    {{- include "kagenti.labels" . | nindent 4 }}
spec:
  gatewayClassName: istio
  listeners:
    - name: mcp
      hostname: "{{ .Values.mcpGateway.hostname }}"
      port: 8080
      protocol: HTTP
      allowedRoutes:
        namespaces:
          from: All
    - name: mcps
      port: 8080
      protocol: HTTP
      hostname: '*.mcp.local'
      allowedRoutes:
        namespaces:
          from: All
---
{{- if .Values.openshift }}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: mcp-gateway
  namespace: "{{ .Values.mcpGateway.namespaces.gatewaySystem }}"
  labels:
    {{- include "kagenti.labels" . | nindent 4 }}
spec:
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  port:
    targetPort: mcp
  to:
    kind: Service
    name: mcp-gateway-istio
    weight: 100
  wildcardPolicy: None
{{- end }}
{{- end }}
